;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        delete-horizontal-space
        sp-delete-char
        sp-splice-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        markdown-exdent-or-delete
        sp-backward-delete-char
        yas-expand
        ))
